# Generated by Django 5.1 on 2024-08-13 11:20

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="app",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("link", models.URLField()),
                ("image", models.ImageField(upload_to="images")),
                ("category_name", models.CharField(max_length=100)),
                ("sub_category_name", models.CharField(max_length=100)),
            ],
        ),
    ]
